CREATE TABLE [dbo].[Page]
(
    [Id] VARCHAR(30) NOT NULL,
    [UserId] VARCHAR(30) NOT NULL,
    [Title] NVARCHAR(255) NOT NULL,
    [Content] NVARCHAR(MAX) NOT NULL,
    [Slug] NVARCHAR(100) NOT NULL,
    [CreationDateTime] DATETIME2 NOT NULL,
    [RevisionDateTime] DATETIME2 NOT NULL,
    CONSTRAINT [PK_Page] PRIMARY KEY CLUSTERED ([Id] DESC)
)
