CREATE TABLE [dbo].[Post]
(
    [Id] VARCHAR(30) NOT NULL, 
    [UserId] VARCHAR(30) NOT NULL,
    [Title] NVARCHAR(255) NOT NULL,
    [Content] NVARCHAR(MAX) NOT NULL,
    [CreationDateTime] DATETIMEOFFSET NOT NULL,
    [RevisionDateTime] DATETIMEOFFSET NOT NULL, 
    CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED ([Id] DESC)
)
